### ISSUE TITLE
Consider remove destructing?

### ISSUE THREAD

**Issue by tunnckoCore** [bahmutov/github-post-release#11]
Hi!

Can you consider removing the destruction? It is in very few places, mainly where the requires are. And in `utils.js` you have modules.exports that uses object shorthand syntax.

Want that, because it fails on Node 4 and i want to have support for it a bit more time.

**Comment by bahmutov** [comment]
If you make pull request with this (add to .travis file too) I will merge it in quickly

**Comment by tunnckoCore** [comment]
Okey, cool! I'll will :)

**Comment by bahmutov** [comment]
Version `1.7.2` has been published to NPM. The full release note can be found at [github-post-release/releases/tag/v1.7.2](https://github.com/bahmutov/github-post-release/releases/tag/v1.7.2).

**Tip:** safely upgrade dependency github-post-release in your project using [next-update](https://github.com/bahmutov/next-update)
