### ISSUE TITLE
scopeless commit, which passed validation with simple-commit-message generates an error on semantic-release post

### ISSUE THREAD

**Issue by AVVS** [bahmutov/github-post-release#17]
I assume the issue is that scope is `null`, but it's optional for the https://github.com/bahmutov/simple-commit-message check. As a result it fails during release notes generation

```
semantic-release ERR! post Error: invalid commit format {
semantic-release ERR! post   "firstLine": "major: first release",
semantic-release ERR! post   "type": "major",
semantic-release ERR! post   "scope": null,
semantic-release ERR! post   "subject": "first release",
semantic-release ERR! post   "id": "8e298fcb72441f33ef12de67312f5fed8e665ce4"
semantic-release ERR! post }
```

**Comment by bahmutov** [comment]
Hmm, this should not happen, can I see a failing test or commit message that causes it?

**Comment by AVVS** [comment]
https://semaphoreci.com/makeomatic/condition-semaphore/servers/npm-git/deploys/7

**Comment by AVVS** [comment]
and commit history - https://github.com/makeomatic/condition-semaphore/commits/master

**Comment by bahmutov** [comment]
The `https://semaphoreci.com/makeomatic/condition-semaphore/servers/npm-git/deploys/7` link gives me 404, but I see history of commits and I see the scopeless commit, hmm.

**Comment by bahmutov** [comment]
Version `1.12.2` has been published to NPM. The full release note can be found at [github-post-release/releases/tag/v1.12.2](https://github.com/bahmutov/github-post-release/releases/tag/v1.12.2).

**Tip:** safely upgrade dependency github-post-release in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by AVVS** [comment]
Thanks for the fix ;)

I guess deploy logs aren't public even for public repos
